// @generated by tools/generate_bridge_bytes.mjs from tools/bridge.wasm — DO NOT EDIT.
//
// The JS<->Wasm-GC bridge module, embedded so every runtime entry point gets it
// without loading a separate `bridge.wasm` asset. Regenerated by `make stage2`.

const BASE64 =
  "AGFzbQEAAAABWQ5eeAFebgFfA38AfwBjAQBgAWMAAX9gAmMAfwF/YAF/AWQAYANjAH9/AGABfwFkAWACYwF/AW5gA2MBf24AYAFjAQF/YAN/f2MBAWQCYAF/AWRsYAFkbAF/AxAPAwQFBgcICQoLDA0FAwcKBQMBAAEH2AEQCnN0cmluZ19sZW4AAApzdHJpbmdfZ2V0AAEKc3RyaW5nX25ldwACCnN0cmluZ19zZXQAAwlhcnJheV9uZXcABAlhcnJheV9nZXQABQlhcnJheV9zZXQABglhcnJheV9sZW4ABwt2YXJpYW50X25ldwAIB2kzMV9uZXcACQdpMzFfZ2V0AAoPYnVsa19zdHJpbmdfbmV3AAsQYnVsa19zdHJpbmdfcmVhZAAMDmJ1bGtfYnl0ZXNfbmV3AA0PYnVsa19ieXRlc19yZWFkAA4GbWVtb3J5AgAKyAIPBgAgAPsPCwkAIAAgAfsNAAsJAEEAIAD7BgALCwAgACABIAL7DgALCQDQbiAA+wYBCwkAIAAgAfsLAQsLACAAIAEgAvsOAQsGACAA+w8LCwAgACABIAL7AAILBgAgAPscCwYAIAD7HQs4AgF/AWQAQQAgAPsGACECQQAhAQJAA0AgASAATw0BIAIgASABLQAA+w4AIAFBAWohAQwACwsgAgsyAQJ/IAD7DyEBQQAhAgJAA0AgAiABTw0BIAIgACAC+w0AOgAAIAJBAWohAgwACwsgAQs6AgF/AWQB0G4gAPsGASECQQAhAQJAA0AgASAATw0BIAIgASABLQAA+xz7DgEgAUEBaiEBDAALCyACCzcBAn8gAPsPIQFBACECAkADQCACIAFPDQEgAiAAIAL7CwH7Fmz7HToAACACQQFqIQIMAAsLIAEL";

export const bridgeBytes = (() => {
  const binary = atob(BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();
