#!/usr/bin/env python3
"""Generate boot/lib/module/core_lib.tw from boot/prelude and boot/stdlib sources."""

import os
import sys
from pathlib import Path
from collections import OrderedDict

VIRTUAL_ROOT = "/__twinkle_core"
CHUNK_LIMIT = 4000

project_root = Path(__file__).resolve().parent.parent
out_path = project_root / "boot" / "lib" / "module" / "core_lib.tw"


def collect_tw_files(directory, prefix, vroot):
    """Recursively collect .tw files with their virtual paths."""
    entries = []
    try:
        items = sorted(os.listdir(directory))
    except OSError:
        return entries

    subdirs = []
    for name in items:
        full = os.path.join(directory, name)
        if name.endswith(".tw") and os.path.isfile(full):
            rel = f"{prefix}/{name}"
            try:
                source = open(full, encoding="utf-8").read()
            except OSError:
                continue
            entries.append((f"{vroot}/{rel}", source))
        elif os.path.isdir(full) and "." not in name:
            subdirs.append(name)

    for name in subdirs:
        full = os.path.join(directory, name)
        entries.extend(collect_tw_files(full, f"{prefix}/{name}", vroot))

    return entries


def build_dir_index(files, vroot):
    """Build a directory index mapping dir paths to child names."""
    pairs = set()
    pairs.add((vroot, ""))

    for virtual_path, _ in files:
        rel = virtual_path[len(vroot) + 1:]
        parts = rel.split("/")
        cur = vroot
        for i, part in enumerate(parts):
            pairs.add((cur, part))
            if i < len(parts) - 1:
                cur = f"{cur}/{part}"

    # Group by directory, sorted
    grouped = OrderedDict()
    for dir_path, name in sorted(pairs):
        if dir_path not in grouped:
            grouped[dir_path] = []
        if name:
            grouped[dir_path].append(name)

    # Deduplicate names within each dir
    result = []
    for dir_path, names in grouped.items():
        seen = []
        for n in names:
            if not seen or seen[-1] != n:
                seen.append(n)
        result.append((dir_path, seen))

    return result


def escape(s):
    """Escape a string for embedding as a Twinkle string literal."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return "".join(out)


def quote(s):
    return f'"{s}"'


def main():
    prelude_files = collect_tw_files(
        str(project_root / "boot" / "prelude"), "prelude", VIRTUAL_ROOT
    )
    stdlib_files = collect_tw_files(
        str(project_root / "boot" / "stdlib"), "stdlib", VIRTUAL_ROOT
    )
    all_files = sorted(prelude_files + stdlib_files, key=lambda f: f[0])
    dir_index = build_dir_index(all_files, VIRTUAL_ROOT)

    buf = []
    buf.append("// Generated by tools/generate_core_lib.py. Do not edit by hand.\n")
    buf.append("use @std.path\n\n")
    buf.append(f"pub root := {quote(VIRTUAL_ROOT)}\n\n")
    buf.append(f'fn join_chunks(chunks: Vector<String>) String {{ chunks.join({quote("")}) }}\n\n')

    # read_text function
    buf.append("pub fn read_text(path_str: String) String? {\n")
    buf.append("  case path.normalize(path_str) {\n")
    for virtual_path, source in all_files:
        escaped = escape(source)
        char_len = len(escaped)
        if char_len <= CHUNK_LIMIT:
            expr = quote(escaped)
        else:
            chunks = []
            j = 0
            while j < char_len:
                end = min(j + CHUNK_LIMIT, char_len)
                # Do not split immediately after a backslash: that would make the
                # generated Twinkle string's closing quote part of the escape.
                if end < char_len and escaped[end - 1] == "\\":
                    end -= 1
                chunks.append(quote(escaped[j:end]))
                j = end
            expr = f'join_chunks([{", ".join(chunks)}])'
        buf.append(f"    {quote(virtual_path)} => .Some({expr}),\n")
    buf.append("    _ => .None,\n")
    buf.append("  }\n}\n\n")

    # list_dir function
    buf.append("pub fn list_dir(path_str: String) Vector<String>? {\n")
    buf.append("  case path.normalize(path_str) {\n")
    for dir_path, names in dir_index:
        names_literal = ", ".join(quote(escape(n)) for n in names)
        buf.append(f"    {quote(dir_path)} => .Some([{names_literal}]),\n")
    buf.append("    _ => .None,\n")
    buf.append("  }\n}\n\n")

    # exists function
    buf.append("pub fn exists(path_str: String) Bool {\n")
    buf.append("  case read_text(path_str) { .Some(_) => true, .None => {\n")
    buf.append("    case list_dir(path_str) { .Some(_) => true, .None => false }\n")
    buf.append("  } }\n")
    buf.append("}\n")

    output = "".join(buf)
    out_path.write_text(output, encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
