#!/usr/bin/env node
// Embeds the JS<->Wasm-GC bridge module into a JS source file so every runtime
// entry point (Node CLI, Deno CLI, web, embeddable lib) gets the bridge without
// loading a separate asset. Run by `make stage2` after the bridge is rebuilt by
// boot/tests/gen_bridge_wasm.tw.
//
//   node tools/generate_bridge_bytes.mjs [input.wasm] [output.mjs]
//
// Defaults: tools/bridge.wasm -> tools/js_runtime/bridge_bytes.mjs.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const input = process.argv[2] ? resolve(process.argv[2]) : resolve(root, "tools/bridge.wasm");
const output = process.argv[3]
  ? resolve(process.argv[3])
  : resolve(root, "tools/js_runtime/bridge_bytes.mjs");

const base64 = readFileSync(input).toString("base64");

// atob + charCodeAt is runtime-agnostic (Node, Deno, browsers) and the bridge
// is tiny, so decoding once at module load is negligible.
const content = `// @generated by tools/generate_bridge_bytes.mjs from tools/bridge.wasm — DO NOT EDIT.
//
// The JS<->Wasm-GC bridge module, embedded so every runtime entry point gets it
// without loading a separate \`bridge.wasm\` asset. Regenerated by \`make stage2\`.

const BASE64 =
  "${base64}";

export const bridgeBytes = (() => {
  const binary = atob(BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();
`;

writeFileSync(output, content);
process.stderr.write(`wrote ${output} (${base64.length} base64 chars)\n`);
